spring.application.name=checkexam
server.port=8081
desc-api-url = http://checkdesc:8080/desc

spring.datasource.url=jdbc:postgresql://postgres:5432/checkexam
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.url=jdbc:postgresql://postgres:5432/checkexam
spring.liquibase.user=postgres
spring.liquibase.password=password
spring.liquibase.change-log=classpath:db/dbchangelog.xml
